language: ruby
cache: bundler
rvm: default
addons:
  postgresql: '9.4'

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:drop db:create db:test:prepare
  - bundle exec rake db:test:load

script:
  # unit and integration tests
  - bundle exec rspec --exclude-pattern "features/**/*_spec.rb"
  # Non-javascript features
  - bundle exec rspec --pattern "features/**/*_spec.rb" --tag ~js
  # Features specs that requires javascript
  - xvfb-run -a bundle exec rspec --pattern "features/**/*_spec.rb" --tag js

# safelist
branches:
  only:
  - master
